
artifacts_root : artifacts

data_ingestion :
  root_dir : artifacts/data_ingestion
  # have to make sure that it's for my MLOPS project
  source_URL : https://github.com/
  # have to check 
  local_data_file : artifacts/data_ingestion/data.zip
  unzip_dir : artifacts/data_ingestion
  
