
artifacts_root : artifacts

data_ingestion :
  root_dir : artifacts/data_ingestion
  # For adding the dataset using a URL
  # https://raw.githubusercontent.com/<username>/<repo>/<branch>/<path-to-file>
  source_URL : https://raw.githubusercontent.com/Singhal-Piyush/Datasets/main/Indian_Flight_Price/dataset.zip

  # dataset link for this project
  #https://www.kaggle.com/datasets/shubhambathwal/flight-price-prediction

  # kaggle_dataset : shubhambathwal/flight-price-prediction
  local_data_file : artifacts/data_ingestion/data.zip
  unzip_dir : artifacts/data_ingestion
  

data_validation:
  root_dir : artifacts/data_validation
  # unzip_data_dir : artifacts/data_ingestion/economy.csv
  unzip_data_files:
    - artifacts/data_ingestion/economy.csv
    - artifacts/data_ingestion/business.csv
  # check for multiple files validation
  STATUS_FILE : artifacts/data_validation/status.txt