
artifacts_root : artifacts

data_ingestion :
  root_dir : artifacts/data_ingestion
  # For adding the dataset using a URL
  # source_URL : https://github.com/
  # dataset link for this project
  #https://www.kaggle.com/datasets/shubhambathwal/flight-price-prediction
  kaggle_dataset : shubhambathwal/flight-price-prediction

  local_data_file : artifacts/data_ingestion/data.zip
  unzip_dir : artifacts/data_ingestion
  
